version: "3.6"

services:
  mock-premier-league:
    container_name: api
    build: ./
    command: npm start
    working_dir: /usr/src/mock-premier-league

    ports:
      - "4000:4000"
    links:
      - mongoDb
      - redis
    volumes:
      - ./:/usr/src/mock-premier-league
      - /usr/src/mock-premier-league/node_modules/
  mongoDb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
